In [1]:
import numpy as np
data= np.array([[26,50000],
                [29,70000],
                [34,55000],
                [31,41000]])

In [3]:
data

array([[   26, 50000],
       [   29, 70000],
       [   34, 55000],
       [   31, 41000]])

In [5]:
from sklearn.preprocessing import MinMaxScaler
scaler= MinMaxScaler()
scaled_data= scaler.fit_transform(data)
scaled_data

array([[0.        , 0.31034483],
       [0.375     , 1.        ],
       [1.        , 0.48275862],
       [0.625     , 0.        ]])

In [7]:
from sklearn.preprocessing import StandardScaler
scaler= StandardScaler()
scaled_data= scaler.fit_transform(data)
scaled_data

array([[-1.37198868, -0.3805212 ],
       [-0.34299717,  1.52208478],
       [ 1.37198868,  0.0951303 ],
       [ 0.34299717, -1.23669388]])